# عملگرهای آرایه ای
# تعریف آرایه

In [3]:
import numpy as np
b = np.array([1,2,3,4,5])
a = np.array([[1,2,3],[5,8,9]])
#print(a)
#print(a.shape)
q = a[:,np.newaxis,:]
print(q)
print(q.shape)

[[[1 2 3]]

 [[5 8 9]]]
(2, 1, 3)


In [30]:
print(a[1])
print(b[1:4])
print(a[1,1:4])
print(a[0:2,2])
print(a[0:2,1:4])

[5 8 9]
[2 3 4]
[8 9]
[3 9]
[[2 3]
 [8 9]]


In [12]:
#a[1][2] 
#or
a[0,1]

2

In [6]:
ar = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(ar.ndim)
print(ar[[0],[0,1]])
print(ar[0][0,1])
ar[1::1]

3
[[1 2 3]
 [4 5 6]]
2


array([[[ 7,  8,  9],
        [10, 11, 12]]])

# کپی کردن آرایه

In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
x = arr1.copy()
y = arr1.view()
arr1[0] = 42
print(type(arr1))
print(x)
print(y)

<class 'numpy.ndarray'>
[1 2 3 4 5]
[42  2  3  4  5]


In [2]:
x.dtype

dtype('int32')

# np.int0

In [5]:
np.int0(x)

C:\Users\Admin\AppData\Local\Temp\ipykernel_14760\3077723794.py:1: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  np.int0(x)


array([1, 2, 3, 4, 5], dtype=int64)

In [4]:
'Text'[1+1]

'x'

# آرایه دوبعدی

In [20]:
np.array([[1,2],[5,6],[1,2],[5,6]],ndmin=2)

array([[1, 2],
       [5, 6],
       [1, 2],
       [5, 6]])

In [6]:
np.array([[1,2],[2,8],[9,2]],dtype="float32")

array([[1., 2.],
       [2., 8.],
       [9., 2.]], dtype=float32)

In [5]:
import numpy as np
arr = np.array((3,2,3),ndmin=4)
arr.ndim
print(arr)


[[[[3 2 3]]]]


In [7]:
np.array([[1,2],[2,8],[9,2]],dtype="uint8")

array([[1, 2],
       [2, 8],
       [9, 2]], dtype=uint8)

In [9]:
np.array([[1,2],[2,8],[9,2]]).dtype

dtype('int32')

# الحاق دو آرایه به هم

In [1]:
import numpy as np
d = np.array([[1,2,3,4],[1,5,8,1]])
f = np.array([[6,9,8,7],[2,8,9,4]])
arr = np.concatenate((d,f),axis=1)
arr2 = np.append(d,f,axis=1)
#arr1 = np.stack((d,f),axis=0)
arr1 = np.hstack((d,f))
#arr =np.hstack((d,f))
print((arr))
print((arr1))
print(arr2)

[[1 2 3 4 6 9 8 7]
 [1 5 8 1 2 8 9 4]]
[[1 2 3 4 6 9 8 7]
 [1 5 8 1 2 8 9 4]]
[[1 2 3 4 6 9 8 7]
 [1 5 8 1 2 8 9 4]]


# آرایه های واحد وصفر

In [9]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [4]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [13]:
np.zeros((3,4)).dtype

dtype('float64')

In [23]:
np.ones((3,4),dtype="uint16")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=uint16)

In [15]:
np.ones((3,4)).dtype

dtype('float64')

# رسم مربع ومستطیل روی تصویر

In [7]:
import cv2
import numpy as np

paper = np.ones((480,640,3),dtype=np.uint8)
paper[:,20:100] = 255
#print(paper[10,25])
paper[:,540:620] = 255
paper[200:280,200:280]=(0,255,0)

cv2.imshow('Paper',paper)
cv2.waitKey()
cv2.destroyAllWindows()

# numpy تبدیل آرایه به نوع 

In [16]:
import numpy as np
a = [1,3]
b = [[3,5],[8,6]]

np.asarray(b)
#np.array(b)


array([[3, 5],
       [8, 6]])

In [19]:
np.asarray([b],dtype=np.float16)

array([[[3., 5.],
        [8., 6.]]], dtype=float16)

# تغییرشکل آرایه

In [5]:
import numpy as np

#a = np.array([[1,2],[8,5],[4,9]],dtype=np.uint8)
a = np.array([(2,3),(4,5),(1,8)],dtype=np.uint8)
print(a)
print(a.shape)

[[2 3]
 [4 5]
 [1 8]]
(3, 2)


In [35]:
c = np.array([1,2,3],ndmin=5)
print(c)
print(c.shape)

[[[[[1 2 3]]]]]
(1, 1, 1, 1, 3)


In [9]:
import numpy as np
z = np.array([1,5,8,6,4,0,78,21,9,11,0,14])
a = np.array([[1,2],[8,5],[4,9]],dtype=np.uint8)
e = np.array([[5,8],[3,7],[8,10],[0,0]])

#print(np.reshape(a,(2,3,1)))## or  a.reshape((2,3))
#print(z.reshape(4,3))
print(z.reshape(2,3,2))
#w = e.reshape(-1,1,1)
#print(w)
#w.shape

[[[ 1  5]
  [ 8  6]
  [ 4  0]]

 [[78 21]
  [ 9 11]
  [ 0 14]]]


In [11]:
e = np.array([[5,8],[3,7],[8,10],[0,0]])
print(e.shape)
e.reshape(-1,2,4)

(4, 2)


array([[[ 5,  8,  3,  7],
        [ 8, 10,  0,  0]]])

In [5]:
import numpy as np

a = np.array([[1,2],[8,5],[4,9]],dtype=np.uint8)
np.reshape(a,(-1))##or  a.reshape((-1,))

array([1, 2, 8, 5, 4, 9], dtype=uint8)

iterating

In [41]:
import numpy as np
q = np.array([[1,3,9],[7,5,1]])
for i in q:
    print(i)

[1 3 9]
[7 5 1]


# تغییر نوع داده ها

##int8,int16,int32,int64 or int0##uint8,uint16,uint32,uint64##float16,float32,float64##complex64,complex128

In [15]:
import numpy as np

from skimage import img_as_ubyte
#from skimage import img_as_afloat
from skimage import img_as_uint
from skimage import img_as_int

a = np.array([1,2,3.5,-3.8])
a.astype ('uint16')
##or
#np.uint32(a)
np.int0(a)
##or
#b = np.array([1,0,0.9,-1])
#img_as_ubyte(b)

C:\Users\Admin\AppData\Local\Temp\ipykernel_15284\3778643919.py:12: DeprecationWarning: `np.int0` is a deprecated alias for `np.intp`.  (Deprecated NumPy 1.24)
  np.int0(a)


array([ 1,  2,  3, -3], dtype=int64)

# مرتب کردن آرایه ها
sorted(x,key=,reverse=)

In [52]:
import numpy as np
x = np.array([5,2,8,9])

sorted(x,reverse=True)

[9, 8, 5, 2]

In [6]:
import numpy as np
x = np.array(['Hello','a','apple','dog','string'])

sorted(x, key = str.lower)
x

array(['Hello', 'a', 'apple', 'dog', 'string'], dtype='<U6')

In [8]:
import numpy as np
x = np.array([['Ali','A',15],
            ['Hasan','A',12],
            ['Zahra','B',10]])

print(sorted(x,key = lambda  x: x[2]))
print(x)

[array(['Zahra', 'B', '10'], dtype='<U11'), array(['Hasan', 'A', '12'], dtype='<U11'), array(['Ali', 'A', '15'], dtype='<U11')]
[['Ali' 'A' '15']
 ['Hasan' 'A' '12']
 ['Zahra' 'B' '10']]


# برگرداندن اندیس های اولیه بعد از مرتب کردن آرایه

In [39]:
import numpy as np
b = np.array([[110,220],
              [250,20],
              [120,200]])
#print(np.sort(b))باید شرط مرتب سازی بصورتی داده شود که خروجی وکتور شود سپس براساس وکتور مقادیر آرایه مرتب شده بذست می آید
print(np.argsort(b[:,1]))
out =b[np.argsort(b[:,1])]
print(out)

[1 2 0]
[[250  20]
 [120 200]
 [110 220]]


In [5]:
b[out]

array([[[[[ 8, 10]],

         [[10,  5]]]],



       [[[[10,  5]],

         [[ 8, 10]]]],



       [[[[10,  5]],

         [[ 8, 10]]]]])

# itemgetter

In [23]:
from operator import itemgetter
import numpy as np
x = np.array([['Ali','A',15],
            ['Hasan','A',12],
            ['Zahra','B',10]])

sorted(x,key = itemgetter(1,2))



[array(['Hasan', 'A', '12'], dtype='<U11'),
 array(['Ali', 'A', '15'], dtype='<U11'),
 array(['Zahra', 'B', '10'], dtype='<U11')]

In [22]:
help(itemgetter)

Help on class itemgetter in module operator:

class itemgetter(builtins.object)
 |  itemgetter(item, ...) --> itemgetter object
 |  
 |  Return a callable object that fetches the given item(s) from its operand.
 |  After f = itemgetter(2), the call f(r) returns r[2].
 |  After g = itemgetter(2, 5, 3), the call g(r) returns (r[2], r[5], r[3])
 |  
 |  Methods defined here:
 |  
 |  __call__(self, /, *args, **kwargs)
 |      Call self as a function.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __reduce__(...)
 |      Return state information for pickling
 |  
 |  __repr__(self, /)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |  
 |  __new__(*args, **kwargs) from builtins.type
 |      Create and return a new object.  See help(type) for accurate signature.



In [21]:
from operator import itemgetter
import numpy as np
x = np.array([['Ali','A',15],
            ['Hasan','A',12],
            ['Zahra','B',10]])

sorted(x,key = itemgetter(0,1),reverse=True)

[array(['Zahra', 'B', '10'], dtype='<U11'),
 array(['Hasan', 'A', '12'], dtype='<U11'),
 array(['Ali', 'A', '15'], dtype='<U11')]

# پیمایش عناصر واندیس های ماتریس

for  i,j  in  np.ndenumerate

# np.unique(labels)
تعداد برچسب هایی که به اجسام داده شده را برمیگرداند

# انتساب داده به لیست

In [39]:

x = [2,5,8]
x.append([1,3,8])
print(x)

[2, 5, 8, [1, 3, 8]]


In [40]:

x = [2,5,8]
x.extend([1,3,8])
print(x)

[2, 5, 8, 1, 3, 8]


# opencv  حداقل و حداکثر داده در 

minLoc,minVal--maxLoc,maxVal = cv2.minMaxLoc(X)

In [1]:
import cv2
import numpy as np
x = np.array([[1,2,3,10,100,20,15,-4,0],[-6,5,6,9,110,4,5,6,2]],dtype='int8')
print(x)
minVal,maxVal,minLoc,maxLoc = cv2.minMaxLoc(x)
print(maxVal,maxLoc)
print(minVal,minLoc)
np.where(x==2,255,0)


[[  1   2   3  10 100  20  15  -4   0]
 [ -6   5   6   9 110   4   5   6   2]]
110.0 (4, 1)
-6.0 (0, 1)


array([[  0, 255,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0, 255]])

# تبدیل آرایه چند بعدی به یک بعدی 

In [42]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
x.flatten()

array([1, 2, 3, 4, 5, 6])

In [43]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [29]:
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
#np.reshape(x,-1) 
x.reshape(-1)

array([1, 2, 3, 4, 5, 6])

# چسباندن آرایه ها به یکدیگر

In [25]:
import numpy as np
d = np.array([1,2,3,4])
f = np.array([6,9,8,7])
arr = np.stack((d,f),axis=1)
print((arr))

[[1 6]
 [2 9]
 [3 8]
 [4 7]]


In [14]:
import numpy as np
d = np.array([[1,2,3,4],[1,5,8,1]])
f = np.array([[6,9,8,7],[2,8,9,4]])
arr = np.stack((d,f),axis=1)
print((arr))

[[[1 2 3 4]
  [6 9 8 7]]

 [[1 5 8 1]
  [2 8 9 4]]]


In [15]:
import numpy as np
d = np.array([1,2,3,4])
f = np.array([6,9,8,7])
arr = np.stack((d,f),axis=0)
print((arr))

[[1 2 3 4]
 [6 9 8 7]]


# چسباندن افقی و عمودی دو تصویر به یکدیگر

In [1]:
import cv2
import numpy as np

im1 = cv2.imread(r"D:\jupiter\OpenCv\face1.jpg")
im2 = cv2.imread(r"D:\jupiter\OpenCv\face2.jpg")
im2 = cv2.resize(im2,(im1.shape[1],im1.shape[0]))
#im1 = np.stack(im1,0)
#im1 = [letterbox(im1,None,new_shape=(416,256),auto=True,interp=cv2.INTER_LINEAR)[0]]
#cv2.imshow("s",im1)
attach = np.stack(im1,0)
print(attach.shape)
cv2.imshow("Attaching two images horizontally",attach)

attach = np.vstack((im1,im2,im2))
cv2.imshow("Attaching two images vertically",attach)

cv2.waitKey()
cv2.destroyAllWindows()


(244, 208, 3)



# تفکیک وادغام کانال های تصویر

a,b,c = cv2.split(array)

array = cv2.merge(a,b,c)

In [22]:
import cv2 
import numpy as np

img = cv2.imread("C:\\Users\\NSC\\Pictures\\Untitled.jpg")
print(img.shape)
(B,G,R) = cv2.split(img)
#print(B)
print(B.shape)
splited = np.vstack((B,G,R))
merged = cv2.merge((B,G,R))
cv2.imshow('Split channels',splited)
cv2.imshow('merged channels',merged)
cv2.waitKey()
cv2.destroyAllWindows()

(288, 1621, 3)
(288, 1621)


# قرینه کردن

cv2.flip(image,flag)

#0 قرینه کردن حول محور افقی

#1 قرینه کردن حول محور عمودی

#-1 قرینه کردن نسبت به هر دو محور

اینکار با 2حلقه تکرار و چیدمان برعکس پیکسل ها در یک ماتریس جدید امکان پذیر است

In [30]:
import cv2

img1 = cv2.imread(r"D:\jupiter\OpenCv\photo_2024-01-22_16-44-05.jpg")


result = cv2.flip(img1,-1)
cv2.imshow("result",result)
cv2.waitKey(0)
cv2.destroyAllWindows()

# عملگرهای ریاضی

جمع و تفریق در پایتون + -

In [2]:
import numpy as np
np.uint8([200])-np.uint8([265])

C:\Users\Admin\AppData\Local\Temp\ipykernel_15568\673114661.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 265 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.uint8([200])-np.uint8([265])


array([191], dtype=uint8)

In [19]:
import numpy as np
np.add(np.uint8([200,200]),np.uint8([100,100])) == np.uint8([200,200])+np.uint8([100,100])


array([ True,  True])

In [3]:
import numpy as np
np.uint8([100,200])-np.uint8([100,256])

C:\Users\Admin\AppData\Local\Temp\ipykernel_15568\1952891903.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.uint8([100,200])-np.uint8([100,256])


array([  0, 200], dtype=uint8)

In [22]:
import numpy as np
np.float32([200])+np.float32([100])

array([300.], dtype=float32)

 opencvجمع وتفریق در 

# یکی از کاربردهای جمع تصاویر(چندفریم پشت سرهم از یک تصویر) حذف نویزهاست

In [59]:
from glob import glob
import numpy as np
import cv2

#result = np.zeros((240,320,3),dtype='uint8')
#print(result.shape)
im_org = cv2.imread(r"D:\jupiter\OpenCv\tt0.jpg")
for i in glob(r"D:\jupiter\OpenCv\tt*.jpg"):
    img = cv2.imread(i)
    print(img.shape)
    #img = cv2.resize(img,(500,500))
    img_org -= img//len(glob(r"D:\jupiter\OpenCv\tt*.jpg"))
    #result = cv2.add(result,img)#opencv جمع دو تصویر با
    #result = np.add(result,img)#numpy  جمع دو تصویر با
cv2.imshow("result",result)
cv2.waitKey(0)
cv2.destroyAllWindows()

(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)
(240, 320, 3)


# opencv ترکیب 2 عکس با 

In [27]:

import numpy as np
import cv2

img1 = cv2.imread(r"D:\jupiter\OpenCv\face1.jpg")
img2 = cv2.imread(r"D:\jupiter\OpenCv\face2.jpg")
img2 = cv2.resize(img2,(img1.shape[1],img1.shape[0]))
result = cv2.add(img1,img2)
cv2.imshow("result",result)
cv2.waitKey(0)
cv2.destroyAllWindows()

# opencv تفریق 2 عکس با

In [28]:

import numpy as np
import cv2

img1 = cv2.imread(r"D:\jupiter\OpenCv\a.tif")# فرمتی که تصاویر را با جزییات نمایش میدهدمخصوص تصاویر پزشکیtif
img2 = cv2.imread(r"D:\jupiter\OpenCv\b.tif")

result = cv2.subtract(img1,img2)
result = result*2 # روشن کردن تصویر
cv2.imshow("result",result)
cv2.waitKey(0)
cv2.destroyAllWindows()

دوربین های ترموگرافی چگالی های اجسام را نشان میدهند و برای یادگیری ماشین بکار میرود

In [24]:
import numpy as np
import cv2

cv2.add(np.uint8([200]),np.uint8([505]))

array([[255]], dtype=uint8)

In [1]:
import numpy as np
import cv2

cv2.add(np.uint16([200]),np.uint16([155]))

array([[355]], dtype=uint16)

In [29]:
import numpy as np
import cv2

cv2.subtract(np.uint8([200]),np.uint8([255]))

array([[0]], dtype=uint8)

In [30]:
import numpy as np
import cv2

cv2.subtract(np.float32([200]),np.float32([255]))

array([[-55.]], dtype=float32)

# روشن وتیره کردن تصویر

In [29]:
import cv2
import numpy as np

img = cv2.imread(r"D:\jupiter\OpenCv\lena.jpeg")
cv2.imshow("Orginal image",img)

M = np.ones(img.shape,dtype="uint8")*100

subtracted = img - M
added = img + M
cv2.imshow("Added by python",added)
cv2.imshow("Subtracted by python",subtracted)

subtracted = cv2.subtract(img , M)
added = cv2.add(img,M)
cv2.imshow("oAdded by Opencv",added)
cv2.imshow("oSubtracted by Opencv",subtracted)

cv2.waitKey()
cv2.destroyAllWindows()

# ترکیب تصویر با ماسک

In [1]:

import numpy as np
import cv2

img1 = cv2.imread(r"D:\jupiter\OpenCv\c.tif")
img2 = cv2.imread(r"D:\jupiter\OpenCv\d.tif")
#print(np.min(img1))
result = img1*(img2//255) # ترکیب یک تصویر بایک تصویر دیگر
cv2.imshow("result",result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
pwd

'C:\\Users\\Admin\\OpenCv'

# ترکیب 2 آرایه

dst = (a*array1)+(B*array2)+y#a,b =[0,1] a+b=1  y=sabet

output = cv2.addWeighted(scr1,alpha,scr2,beta,gamma)

In [68]:
import cv2

img1 = cv2.imread(r"D:\jupiter\OpenCv\face1.jpg")
img2 = cv2.imread(r"D:\jupiter\OpenCv\face2.jpg")
img2 = cv2.resize(img2,(img1.shape[1],img1.shape[0]))

output = cv2.addWeighted(img1,0.6,img2,0.4,20)
cv2.imshow("tarkib",output)
cv2.waitKey()
cv2.destroyAllWindows()

# ماکزیمم و مینیمم در آرایه

پایتون

In [41]:
a = [1,5,6,9]
max(a)
min(a)

1

opencv,numpy

In [34]:
import cv2
import numpy as np

a = np.array([[1,4,0],[-3,10,7]])
b = np.array([[9,-22,5],[11,6,2]])

print(np.maximum(a,b))
print(np.maximum(a,2))
#print(np.minimum(a,b))

print(np.max(a))
print(np.min(b))

#print(cv2.max(a,b))
#print(cv2.min(a,b))
print(cv2.max(a,2))


[[ 9  4  5]
 [11 10  7]]
[[ 2  4  2]
 [ 2 10  7]]
10
-22
[[ 2  4  2]
 [ 2 10  7]]


# اندیس کمترین وبیشترین داده ها

np.argmin(a)

np.argmax(a)

In [7]:
import numpy as np

a = np.array([[[1,4,0],[-3,10,7]]])
b = np.array([9,-22,5,1,11,6,2])
print(np.argmin(a))
print(np.argmax(b))

3
4


# میانگین وانحراف معیار

نسبت مجموع تمام درایه های یک آرایه به تعداد کل درایه ها را میانگین گویند
مقدار تغییر یا پراکندگی داده ها ازمیانگین را انحراف معیار گویندوبا آلفا نمایش میدهند

 mean , std درپایتون
    
meanStdDev/ opencv در     

In [4]:
import cv2
import numpy as np

a = np.array([1,2,3,4,5,6,6,5,4])
print(a.mean())
print(a.std())

print(cv2.meanStdDev(a))

4.0
1.632993161855452
(array([[4.]]), array([[1.63299316]]))


# بریدن آرایه

np.clip(x,a,b)#بازه بالا وپایینa,b

In [12]:
import numpy as np
import cv2

x = np.array([10,2,3,4,5,6,7,8,9,10,11,2,1,12,13,14])
#x = cv2.imread("C:\\Users\\NSC\\Pictures\\Fire\\7.png")
x_new = np.clip(x,3,10)
#cv2.imshow("s",x_new)
#cv2.waitKey(0)
#cv2.destroyAllWindows()
#np.clip(x,None,7)
x_new

array([10,  3,  3,  4,  5,  6,  7,  8,  9, 10, 10,  3,  3, 10, 10, 10])

# رنگ آمیزی یک تصویر برحسب رنگ های تصویر دیگر

In [26]:
import cv2
import numpy as np

def devation(image):
    (L,A,B) = cv2.split(image)
    (Lmean,Lstd) = (L.mean(),L.std())
    (Amean,Astd) = (A.mean(),A.std())
    (Bmean,Bstd) = (B.mean(),B.std())
    
    return (Lmean,Lstd,Amean,Astd,Bmean,Bstd)

def color_transfer(source,target):
    source = cv2.cvtColor(source,cv2.COLOR_BGR2LAB)
    target = cv2.cvtColor(target,cv2.COLOR_BGR2LAB)
    source = source.astype("float32")
    target = target.astype("float32")
    (Lmean_src,Lstd_src,Amean_src,Astd_src,Bmean_src,Bstd_src) = devation(source)
    (Lmean_tar,Lstd_tar,Amean_tar,Astd_tar,Bmean_tar,Bstd_tar) = devation(target)
    
    (l,a,b) = cv2.split(target)
    l -=Lmean_tar
    a -=Amean_tar
    b -=Bmean_tar
    
    l = (Lstd_tar / Lstd_src) * l
    a = (Astd_tar / Astd_src) * a
    b = (Bstd_tar / Bstd_src) * b
    
    l += Lmean_src
    a += Amean_src
    b += Bmean_src
    
    l = np.clip(l,0,255)
    a = np.clip(a,0,255)
    b = np.clip(b,0,255)
    
    transfer = cv2.merge([l,a,b])
    transfer.astype("uint8")
    transfer = cv2.cvtColor(transfer,cv2.COLOR_LAB2BGR)
    return transfer


source = cv2.imread("C:\\Users\\NSC\\Pictures\\car\\1.png")
target = cv2.imread("C:\\Users\\NSC\\Pictures\\car\\8.png")
transfreed = color_transfer(source,target)

cv2.imshow('Source',source)
cv2.imshow('Target',target)
cv2.imshow('Transfreed',transfreed)

cv2.waitKey(0)
cv2.destroyAllWindows()
    

# تعداد درایه های غیر صفر

cv2.countNonZero(x)#تک کاناله یا باینری

In [21]:
import cv2
import numpy as np
x = np.array([1,5,0,-4,9,11,3,0,0])
cv2.countNonZero(x)

6

# تبدیل عدد به رشته وبرعکس

eval('') , str()

In [28]:
print(eval("100"))
str(100)

100


'100'

# نرمالیزه کردن آرایه
norm() = جذرمجموع مربع های اعضا-نرم آرایه

normalize() = برای نرمالایز کردن-هر عضو تقسیم بر نرم

output = cv2.normalize(src,dst,alpha,beta,normType)

src آرایه نرمالایز نشده

dstآرایه خروجی که هم اندازه ورودی است

alpha,betaاز چپ به راست -حد پایین و بالای دامنه ای که داده ها باید در آن محدوده قرار بگیرند

normtype پرچم تعیین کننده نحوه محاسبه نرم که 4حالت دارد

1-cv2.NORM_INFنرم برابر است با بزرگترین قدر مطلق اعضا

2-cv2.NORM_L1نرم برابر با مجموع قدر مطلق اعضا

3-cv2.NORM_L2نرم برابر با جذرمجموع مربع های اعضا که پیشفرض نیز است

4-cv2.NORM_MINMAXنرم برحسب آلفا و بتا انجام میشود

In [25]:
import cv2
import numpy as np
x = np .array([4,0,13,-4,22,255,1000,0,6],dtype="float32")
cv2.norm(x)

1032.34974693657

In [26]:
cv2.normalize(x,x)
print(x)
print(cv2.norm(x))

[ 0.00387466  0.          0.01259263 -0.00387466  0.02131061  0.2470093
  0.96866393  0.          0.00581198]
0.999999965117357


In [34]:
import cv2
import numpy as np
x = np .array([4,0,13,-4,22,255,128,0,6],dtype="float32")
cv2.normalize(x,x,0,100,cv2.NORM_MINMAX)

array([  3.088803 ,   1.5444015,   6.5637064,   0.       ,  10.0386095,
       100.       ,  50.965252 ,   1.5444015,   3.8610039], dtype=float32)

In [7]:
import cv2
import numpy as np
x = np .array([4,0,13,-4,22,255,128,0,6],dtype="float32")
cv2.normalize(x,x,0,200,cv2.NORM_MINMAX)

array([  6.177606 ,   3.088803 ,  13.127413 ,   0.       ,  20.077219 ,
       200.       , 101.930504 ,   3.088803 ,   7.7220078], dtype=float32)

# تولید اعداد تصادفی

np.random.randint(low,hight,size(ابعادارایه یا ماتریس))برای تولید رنگ یا مختصات تصادفی

np.random.randn(d0,d1,...,dn)برای ایجاد نویز-اعداد با میانگین0وواریانس1-ایجادمیکند-dابعادماتریس

# افزودن نویز به تصویر

In [32]:
import cv2
import numpy as np

image = cv2.imread("s.png")
img = np.float64(image)
#print(*img.shape)
#print(img)

noise = np.random.randn(*img.shape)*80
#print(noise)
noisy_img = img+noise
noisy_img = np.uint8(np.clip(noisy_img,0,255))
#noisy_img = np.uint8(noisy_img)

cv2.imshow('Apply noise to original image',np.hstack ([image,noisy_img]))
cv2.imshow('Noise',noise)
cv2.waitKey()
cv2.destroyAllWindows()

In [37]:
import numpy as np
np.random.randn(3,2,1,1)

array([[[[ 0.81437877]],

        [[ 0.05785976]]],


       [[[ 0.21239549]],

        [[ 0.42696458]]],


       [[[-0.35192032]],

        [[ 0.30363256]]]])

In [41]:
import numpy as np
np.random.randint(1,10,(2,3,4))

array([[[4, 8, 8, 2],
        [4, 2, 9, 8],
        [6, 6, 5, 3]],

       [[9, 8, 4, 7],
        [6, 2, 7, 7],
        [6, 3, 3, 3]]])

# inRange تابع 

output = cv2.inRange(src,lowerb,upperb)بررسی حضور یاعدم حضورداده ها در بازه مورد نظر را دارد


In [28]:
import cv2
import numpy as np

a = np.array([1,2,3,4,5,6,7,8,9,10])
cv2.inRange(a,2,6)

array([[  0],
       [255],
       [255],
       [255],
       [255],
       [255],
       [  0],
       [  0],
       [  0],
       [  0]], dtype=uint8)

# عملگرهای منطقی

bitwise_xor()

bitwise_not()

bitwise_or(img1,img2,mask=)

bitwise_and(img1,img2,mask=)

In [42]:
import cv2
cam = cv2.VideoCapture(0)
lowerG = (30,100,45)
upperG = (70,255,240)

while True:
    if cv2.waitKey(1) == 27:
        break
    _,frame = cam.read()
    frame_hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV)
    mask = cv2.inRange(frame_hsv,lowerG,upperG)
  #  print(mask)
    green_obj = cv2.bitwise_and(frame,frame,mask=mask)
    #print(green_obj)
    cv2.imshow("Original Frame",frame)
    cv2.imshow("Mask",mask)
    cv2.imshow("Dtecting Green Objects",green_obj)
cam.release()
cv2.destroyAllWindows()

In [7]:
(tuple(input("please Enter shape of tensor:")))

please Enter shape of tensor:12365


('1', '2', '3', '6', '5')